### ISSUE TITLE
matchExpressions label value validate failed for the specific value `cls-27rq50l2`

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#133]
#### What happened:

```yaml
  subscribers:
  - clusterAffinity:
      matchExpressions:
      - key: clusters.clusternet.io/cluster-name
        operator: In
        values:
        - cls-27rq50l2
```

```
E0923 10:46:39.327280       1 subscription.go:358] error syncing 'clusternet-subs/wordpress3-sub': values[0][cls-27rq50l2]: Invalid value: "clusters.clusternet.io/cluster-name": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), requeuing
```

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by DanielXLee** [comment]
This is a weird issue. Keep the issue open and wait for the follow-up test results

**Comment by DanielXLee** [comment]
false alarm， this issue cause by a bad test case
```
  subscribers:
  - clusterAffinity:
      matchLabels:
        cls-27rq50l2: clusters.clusternet.io/cluster-name
```
