### ISSUE TITLE
when apply an exist deployment, return error

### ISSUE THREAD

**Issue by silenceper** [clusternet/clusternet#174]
#### What happened:
when apply an exist deployment, return error
```
Error from server (NotFound): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"labels\":{\"clusternet-app\":\"multi-cluster-nginx\"},\"name\":\"my-nginx\",\"namespace\":\"foo\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"nginx\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"nginx\"}},\"spec\":{\"containers\":[{\"image\":\"nginx:1.14.2\",\"name\":\"nginx\",\"ports\":[{\"containerPort\":80}]}]}}}}\n"},"labels":{"aa":null}},"spec":{"template":{"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}]}]}}}}
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "my-nginx", Namespace: "foo"
for: "nginx-deployment-foo.yaml": deployments.shadow "my-nginx" not found
```

```
kubectl clusternet apply -f deploy.yaml
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: foo
  labels:
    clusternet-app: multi-cluster-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
```
{
  "programName": "clusternet-hub",
  "major": "0",
  "minor": "5+",
  "gitVersion": "v0.5.0-11-g6112b08",
  "gitCommit": "6112b08eb21357e669f3f390b2eea56ab729d72e",
  "gitTreeState": "clean",
  "buildDate": "2021-11-03T08:05:21Z",
  "goVersion": "go1.14.15",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:
