### ISSUE TITLE
Support add `username`, `password` to repo in HelmChart

### ISSUE THREAD

**Issue by silenceper** [clusternet/clusternet#186]
#### What would you like to be added:
Support add `username`, `password` to repo in HelmChart

#### Why is this needed:
```
apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: example
  namespace: default
spec:
  repo: https://private-repo.com/test
  username: xxx
  password: xxx
  chart: example
  version: 0.0.1
  targetNamespace: abc
```

**Comment by silenceper** [comment]
/assign @silenceper

I can contribute this feature.

**Comment by dixudx** [comment]
```yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: example
  namespace: default
spec:
  repo: https://private-repo.com/test
  username: xxx
  password: xxx
  chart: example
  version: 0.0.1
  targetNamespace: abc
```

@silenceper This is not secure. The credentials here are visible to anyone with `get`/`list` roles of `HelmChart`.

**Comment by silenceper** [comment]
I agree.

maybe can chagne to this:
```
apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: example
  namespace: default
spec:
  repo: https://private-repo.com/test
  authSecretName: my-private-repo-auth
  authSecretNamespace: kube-system
  chart: example
  version: 0.0.1
  targetNamespace: abc
```
```
apiVersion: v1
data:
  username: xxx
  password: xxxx
kind: Secret
metadata:
  name: my-private-repo-auth
  namespace: kube-system
```

**Comment by dixudx** [comment]
Another thing you need to take into consideration is if the sync mode is `Pull`, how to pass down those credentials.

**Comment by silenceper** [comment]
> Another thing you need to take into consideration is how to pass down those credentials when the sync mode is `Pull`.

My idea is to add `get` secret permission for serviceAccount when CRR approve.

The namespace of this secret can be configured in the hub like `--helm-repo-secret-namespace`, and all secrets involving the helm chart repo are placed under this namespace.

```
apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: example
  namespace: default
spec:
  repo: https://private-repo.com/test
  authSecretName: my-private-repo-auth # Under the `--helm-repo-secret-namespace` namespace
  chart: example
  version: 0.0.1
  targetNamespace: abc
```
