### ISSUE TITLE
target cluster helm release does not upgrade when the HelmChart spec.version changed

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#200]
#### What happened:
```yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: nginx
  namespace: kube-system
spec:
  chart: nginx
  repo: http://xxx.xxx.xxx.xxx
  targetNamespace: kube-system
  version: 0.2.0 --> update here from 0.1.0 to 0.2.0
```
target cluster helm release does not change
#### What you expected to happen:
target cluster helm release upgrade to version 0.2.0
#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:
