### ISSUE TITLE
hub cannot sync change to child when remove a line data from a configmap

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#262]
#### What happened:
delete a line data from a configmap, the hub cannot sync this change to a child cluster

example:
create a cm 
```
apiVersion: v1
data:
  aa: bb
  cc: dd
kind: ConfigMap
metadata:
  name: test-cm
  namespace: test
```
delete `data.cc` from this configmap, hub cannot sync this change to the child cluster.
```
apiVersion: v1
data:
  aa: bb
kind: ConfigMap
metadata:
  name: test-cm
  namespace: test
```

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:
