### ISSUE TITLE
configure helm chart deploy order 

### ISSUE THREAD

**Issue by jasine** [clusternet/clusternet#273]
#### What would you like to be added:

configure helm chant deploy order 

#### Why is this needed:

we can ship multiple charts in the feeds field of subscription, but some helm chats may have dependency, for example, we have to deploy monitor crd before servicemonitor resource can be deployed, so what if define a weight to measure helm deploy order in subscription.

besides on, when  a new cluster joined to parent cluster, all valid charts will be deployed, and they also unordered, which may cause problems

**Comment by dixudx** [comment]
> configure helm chart deploy order

In Helm, one chart may depend on any number of other charts. These dependencies can be dynamically linked using the dependencies field in `Chart.yaml`.

```
# Chart.yaml
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "https://example.com/charts"
- name: memcached
  version: "3.2.1"
  repository: "https://another.example.com/charts"
```

> what if define a weight to measure helm deploy order in subscription

I'd prefer using Helm `dependencies` to help keep the deploy order.
