### ISSUE TITLE
clusterAffinity of Globalization not working

### ISSUE THREAD

**Issue by jasine** [clusternet/clusternet#333]
#### What happened:

I want to override different configs for a subscription  according to different labels of mcls, so I  created two Globalization and use `matchLabels` of `clusterAffinity` field to query different mcls , but `clusterAffinity` does  not  work, all overrides of Globalizations merged in target `description`

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):0.9.1
    - Clusternet-hub version (user `clusternet-hub --version=json`): 0.9.1
- Kubernetes version (use `kubectl version`): k3s  1.22
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04

**Comment by dixudx** [comment]
@jasine Could you please share your `Globalization` specifications?

**Comment by jasine** [comment]
@dixudx 

```yaml
spec:
  clusterAffinity:
    matchLabels:
      accelerator: npu
  feed:
    apiVersion: apps.clusternet.io/v1alpha1
    kind: HelmChart
    name: dipper
    namespace: dipper
  overridePolicy: ApplyNow
  overrides:
  - name: override-npu-config
    type: Helm
    value: |-
      accelerator:
        npu: true
      logLevel: debug
      imagePullPolicy: Always
      imagePullSecret:
        username: "xxxxx"
        password:  xxxxx
      .... # other configs
  priority: 600
```
