### ISSUE TITLE
Add more status informations for ManagedCluster.Status

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#47]
#### What would you like to be added:
Example:

```
status:
  allocatable:
    cpu: "8"
    memory: 15753Mi
  capacity:
    cpu: "8"
    memory: 15753Mi
  clusterCidr: 10.44.0.0/24
  serviceCidr: 10.45.0.0/24
```
