### ISSUE TITLE
Cannot create HelmRelease 

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#473]
#### What happened:
Create an nginx-ingress HelmChart and create a subscription with empty clusterAffinity. when a cluster is registered, sometimes the HelmRelease cannot be created. The cause is "target cluster has disabled AppPusher". 
```yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
  name: nginx-test
  namespace: default
spec:
  feeds:
  - apiVersion: clusters.clusternet.io/v1beta1
    kind: HelmChart
    name: nginx-ingress
    namespace: kube-system
  subscribers:
  - clusterAffinity: {}
 ```

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:
