### ISSUE TITLE
What the predictor want to do ?

### ISSUE THREAD

**Issue by victory460** [clusternet/clusternet#479]
K8S scheduler plugin consist of `Filter、Score、Reserve、PreBind、Bind.`
What the `predictor` want to do ?

<img width="494" alt="image" src="https://user-images.githubusercontent.com/30213558/188861728-08caec47-d66e-4551-8e48-b9d6989666f1.png">

```

// Step 2: Predict max available replicas if necessary.
	availableList, err := predictReplicas(ctx, fwk, state, sub, finv, feasibleClusters)
```

What exactly the replicas of ?   feed 、cluster or others ?

**Comment by victory460** [comment]
Thanks.

**Comment by victory460** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/30213558/189015742-b94b7b84-654a-44e6-b154-0a39d0d29a35.png">

`schedulingStrategy` was processed in `Assign` plugin, which plugin do label select  function such as `clusterAffinity.matchLabel` ？

```
spec:
  subscribers: # defines the clusters to be distributed to
    - clusterAffinity:
        matchLabels:
          clusters.clusternet.io/cluster-id: dc91021d-2361-4f6d-a404-7c33b9e01118 # PLEASE UPDATE THIS CLUSTER-ID TO YOURS!!!
      weight: 1 # Deployment bar/my-nginx will have 2 replicas running in this cluster
    - clusterAffinity:
        matchLabels:
          clusters.clusternet.io/cluster-id: 5f9da921-0437-4fea-a89d-42aa1ede9b25 # PLEASE UPDATE THIS CLUSTER-ID TO YOURS!!!
      weight: 2 # Deployment bar/my-nginx will have 4 replicas running in this cluster
  schedulingStrategy: Dividing
  dividingScheduling:
    type: Static
```
