### ISSUE TITLE
Dynamic dividing scheduling panic

### ISSUE THREAD

**Issue by yinsenyan** [clusternet/clusternet#486]
#### What happened:
clusternet-scheduler panic
If apply a subs with dynamic dividing scheduling just like 
```
spec:
  dividingScheduling:
    dynamicDividing:
      strategy: Spread
    type: Dynamic
  schedulingStrategy: Dividing
```

clusternet-scheduler will panic at [here](https://github.com/clusternet/clusternet/blob/main/pkg/scheduler/framework/interfaces/types.go#L140)  with frist scheduling job

#### What you expected to happen:
Don't panic, and scheduling success.
#### How to reproduce it (as minimally and precisely as possible):
Replace test code [here](https://github.com/clusternet/clusternet/blob/main/pkg/scheduler/framework/interfaces/types_test.go#L10) to ``` BindingClusters: []string{}, ```, and run test code will reproduce. 
#### Environment:
- Clusternet version: 0.11.0 and main
- Kubernetes version (use `kubectl version`): 1.20.1
