### ISSUE TITLE
managed cluster still show alive forever even if agent get removed from target cluster

### ISSUE THREAD

**Issue by huxiaoliang** [clusternet/clusternet#56]
```
 k get mcls -A
NAMESPACE          NAME                       CLUSTER ID                             SYNC MODE   KUBERNETES   READYZ   AGE
clusternet-9p2pf   clusternet-cluster-pn4g4   e0a73457-33c1-4528-b47f-caf422d29760   Push        v1.21.1      true     39h
```

@dixudx  I know the cluster heartbeat triggered by agent which cause cluster status show alive forever even if agent get removed from target cluster.  This issue cause CLI user and third party integrator confuse,  could you please do this enhancement in clustenet, thanks in advance.

**Comment by huxiaoliang** [comment]
after I stop 3 agent,  20 minutes later,  I still can't get correct status of managed cluster,  I hope healthz and livez both set to `false`

issue 1: 
```
root@VM-121-42-ubuntu:~/clusternet# kubectl get mcls clusternet-cluster-p827b -n clusternet-9bv8g  
NAME                       CLUSTER ID                             SYNC MODE   KUBERNETES   READYZ   AGE
clusternet-cluster-p827b   7bda1908-0f8c-46fb-a477-6004db52c063   Dual        v1.21.1      true     57m
```

issue 2: 
```
  conditions:
  - lastTransitionTime: "2021-09-06T13:01:46Z"
    message: Clusternet agent stopped posting cluster status.
    reason: ClusterStatusUnknown
    status: Unknown
    type: Ready
  healthz: true
  k8sVersion: v1.21.1
  lastObservedTime: "2021-09-06T12:10:31Z"
  livez: true
```
