### ISSUE TITLE
Update subscription feeds when remove an application template

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#66]
#### What would you like to be added:
When the application template is deleted, the application feeds should be removed from the subscription.

Example:
// Delete mysql chart
kubectl delete charts mysql -n default
// mysql feed should be delete
```yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
....
  feeds:
  - apiVersion: apps.clusternet.io/v1alpha1
    kind: HelmChart
    name: mysql
    namespace: default
```
