### ISSUE TITLE
deployed application will be uninstalling when upgrade clusternet to new version v0.15.0

### ISSUE THREAD

**Issue by DanielXLee** [clusternet/clusternet#664]
#### What happened:
Deploy a demo application with clusternet v0.14.0, then upgrade clusternet to v0.15.0, and the application will be uninstalled. It seems that the `Base` name has changed, related PR: https://github.com/clusternet/clusternet/pull/642

#### What you expected to happen:
The deployed application doesn't affect when upgrading clusternet version

#### How to reproduce it (as minimally and precisely as possible):
1. Install the old version clusternet v0.14.0 with the local-running.sh
2. Deploy an application as following yaml:
```yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: HelmChart
metadata:
  name: mysql # this name will be used as Helm release name as well
  namespace: default
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: mysql
  version: 9.2.0
  targetNamespace: default

---
apiVersion: apps.clusternet.io/v1alpha1
kind: Subscription
metadata:
  name: app-demo
  namespace: default
spec:
  subscribers: # defines the clusters to be distributed to
    - clusterAffinity:
        matchLabels:
          clusters.clusternet.io/cluster-name: child1
  feeds: # defines all the resources to be deployed with
    - apiVersion: apps.clusternet.io/v1alpha1
      kind: HelmChart
      name: mysql
      namespace: default
```

3. Upgrade clusternet
```bash
helm upgrade --install clusternet-scheduler clusternet/clusternet-scheduler -n clusternet-system
helm upgrade --install clusternet-hub clusternet/clusternet-hub -n clusternet-system
helm upgrade --install clusternet-controller-manager clusternet/clusternet-controller-manager -n clusternet-system
```

```bash
kubectl get hr -A -w
NAMESPACE          NAME                          CHART   VERSION   REPO                                 STATUS     AGE
clusternet-dws4r   app-demo-helm-default-mysql   mysql   9.2.0     https://charts.bitnami.com/bitnami   deployed   98s
clusternet-dws4r   app-demo-default-helm-default-mysql   mysql   9.2.0     https://charts.bitnami.com/bitnami              0s
clusternet-dws4r   app-demo-default-helm-default-mysql   mysql   9.2.0     https://charts.bitnami.com/bitnami              0s
clusternet-dws4r   app-demo-helm-default-mysql           mysql   9.2.0     https://charts.bitnami.com/bitnami   deployed   2m17s
clusternet-dws4r   app-demo-helm-default-mysql           mysql   9.2.0     https://charts.bitnami.com/bitnami   deployed   2m22s
clusternet-dws4r   app-demo-helm-default-mysql           mysql   9.2.0     https://charts.bitnami.com/bitnami   uninstalling   2m22s
clusternet-dws4r   app-demo-default-helm-default-mysql   mysql   9.2.0     https://charts.bitnami.com/bitnami   uninstalling   5s
clusternet-dws4r   app-demo-helm-default-mysql           mysql   9.2.0     https://charts.bitnami.com/bitnami   uninstalling   2m26s

^C#
kubectl get hr -A
NAMESPACE          NAME                                  CHART   VERSION   REPO                                 STATUS         AGE
clusternet-dws4r   app-demo-default-helm-default-mysql   mysql   9.2.0     https://charts.bitnami.com/bitnami   uninstalling   12m
```
#### Environment:
- Clusternet version: v0.14.0
- Kubernetes version (use `kubectl version`): v1.22.0
