### ISSUE TITLE
clusternet hub can not create resource with apiversion that different from prioritized apiversion

### ISSUE THREAD

**Issue by xrmzju** [clusternet/clusternet#677]
- in k8s v1.22,  `autoscaling/v1 `  is prioritized for horizontalpodautoscalers 
``` 
kubectl api-resources --api-group=autoscaling
NAME                       SHORTNAMES   APIVERSION       NAMESPACED   KIND
horizontalpodautoscalers   hpa          autoscaling/v1   true         HorizontalPodAutoscaler
``` 
- create horizontalpodautoscalers with apiversion  `autoscaling/v2beta2`, kubectl(kube-apiserver) resulted with success, but kubectl-clusternet(clusternet-hub) report  with `the API version in the data (autoscaling/v2beta2) does not match the expected API version (autoscaling/v1)`. 
``` 
# use kubectl clusternet
kubectl clusternet apply -f hpa.yaml
Error from server (BadRequest): error when creating "hpa.yaml": the API version in the data (autoscaling/v2beta2) does not match the expected API version (autoscaling/v1)

# use kubectl 
kubectl apply -f hpa.yaml
horizontalpodautoscaler.autoscaling/test-hpa created
```
- hpa.yaml
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: test-hpa
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - pods:
      metric:
        name: pod_cpu_limit_usage
      target:
        averageValue: 50m
        type: AverageValue
    type: Pods
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment
```
#### Environment:
- Clusternet version:
    - Clusternet-hub version (user `clusternet-hub --version=json`): v0.10.0
   
- Kubernetes version (use `kubectl version`): v1.22.5
