### ISSUE TITLE
Adopting a Standardized ClusterInventory API from SIG Multi-Cluster

### ISSUE THREAD

**Issue by dixudx** [clusternet/clusternet#721]
#### What would you like to be added:
kind/feature

#### Why is this needed:

Currently Clusternet is using a self-defined CRD [ManagedCluster](https://github.com/clusternet/clusternet/blob/main/pkg/apis/clusters/v1beta1/types.go#L330) to declare a cluster, including cluster ID, labels, access point, status, etc. This CRD is used for cluster managements and multiple cluster scheduling.

While this kind of cluster definitions can be seen and needed in multiple projects. They have much in common, but they are not interactable. It makes harder for Clusternet itself to be compatible with other Kubernetes tools and services, such as Argo, Flux, etc. Also other projects are not easy to directly integrate with Clusternet via a common and standardized API.

Once sig multi-cluster has reached an agreement on below `ClusterInventory API`, Clusternet would like to adopt and migrate to it. 

```yaml
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ClusterInventory
metadata:
 name: some-cluster
spec:
 accessObjectRefs: # optional object points to the resource that declares how to access the cluster
 - group: someGroup
   resource: someResource
   name: someName
   namespace: someNamespace
   type: KUBECONFIG
 taints:
   - key: key1
     value: value1
     effect: NoSchedule
     addTime: xxx
 healthinessProbe:
   heartbeatIntervalSeconds: 60
status:
 version:
   kubernetes: 1.26.1
 resources: # total resources of a cluster
   capacity:
     cpu: 12
     memory: 12Gi
   allocatable:
     cpu: 10
     memory: 16Gi
 properties:
   - name: clusterset.k8s.io
     value: some-clusterset
 conditions:
   - type: Healthy
     status: True
     lastTransitionTime: "2023-05-08T07:58:55Z"
     message: ""
```

Since this ClusterInventory API has much in common with our current `ManagedCluster`,  there won't be too many inconsistencies with current working flows in Clusternet.
