### ISSUE TITLE
Globalization enhancement, support cluster affinity and json/yaml text field override

### ISSUE THREAD

**Issue by abstractmj** [clusternet/clusternet#882]
#### What would you like to be added:

feature 1:
globalization add cluster affinity to select target cluster

```yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: Globalization
metadata:
  name: nginx-global-overrides-demo
spec:
  priority: 600
  feed:
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx
    namespace: foo
  clusterAffinity:
    region: shanghai
  overrides:
    - name: add-update-labels
      type: MergePatch
      # Value is a YAML/JSON format patch that provides MergePatch to current resource defined by feed.
      # This override adds or updates some labels.
      value: |-
        metadata:
          labels:
            some-label: some-value
            another-label: another-value
```

feature: 2:
overrides support field path to choose configmap or secret data field

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
  namespace: foo
data:
  db.conf: |
    mysql:
      .....
      address: "default.mysql.db"
    otherconfigs:
      ....
---

apiVersion: apps.clusternet.io/v1alpha1
kind: Globalization
metadata:
  name: db-conf-overrides
spec:
  # Priority is an integer defining the relative importance of this Globalization compared to others.
  # Lower numbers are considered lower priority.
  # Override values in lower Globalization will be overridden by those in higher Globalization.
  # (Optional) Default priority is 500.
  priority: 600
  feed:
    apiVersion: v1
    kind: ConfigMap
    name: db-conf
    namespace: foo
  clusterAffinity:
    region: shanghai
  overrides: # defines all the overrides to be processed with
    - name: modify-db-addreess
      fieldPath: /data/db.conf
      type: MergePatch
      value: |-
        mysql:
          address: "shanghai.mysql.db:3306"
```

#### Why is this needed:

If I have a configmap that stores the DB address for each region, and this DB address is different in each cluster. Assuming I have 2 regions, each with 3 clusters, I would need to define 6 localizations through Clusternet, and each localization would need to specify the namespace of the member cluster, which feels quite inconvenient.

**Comment by dixudx** [comment]
> globalization add cluster affinity to select target cluster

Already supported. This is built-in by default.

https://github.com/clusternet/clusternet/blob/eec356a06ee711fe4f4cf36e855be456b787ef91/pkg/apis/apps/v1alpha1/globalization.go#L39-L53

**Comment by abstractmj** [comment]
Indeed, adding a field to indicate the format would make it more reasonable. 

```yaml
apiVersion: apps.clusternet.io/v1alpha1
kind: Globalization
metadata:
  name: db-conf-overrides
spec:
  # Priority is an integer defining the relative importance of this Globalization compared to others.
  # Lower numbers are considered lower priority.
  # Override values in lower Globalization will be overridden by those in higher Globalization.
  # (Optional) Default priority is 500.
  priority: 600
  feed:
    apiVersion: v1
    kind: ConfigMap
    name: db-conf
    namespace: foo
  clusterAffinity:
    region: shanghai
  overrides: # defines all the overrides to be processed with
    - name: modify-db-addreess
      fieldPath: /data/db.conf
      fieldFormat: yaml
      type: MergePatch
      value: |-
        mysql:
          address: "shanghai.mysql.db:3306"
```
